### ISSUE TITLE
How can we capture the click:outside event?

### ISSUE THREAD

**Issue by harry-73** [kieuminhcanh/vuetify-notifier#17]

**Comment by kieuminhcanh** [comment]
Could you give more details? Which feature are you using? Toast?

**Comment by harry-73** [comment]
Sorry.

It is with Confirm. I would to know when a user clicks outside the Dialog to close it. `VOverlay` 
provides `click:outside` event for this purpose.
Before v2, I used `notifier.confirm().catch(/* code */)` to do it.

**Comment by kieuminhcanh** [comment]
The confirm dialog is close if you're click outside. 
![image](https://github.com/user-attachments/assets/9d058a2c-be8f-4944-9f32-9e4c00426302)

**Comment by harry-73** [comment]
Yes but I want to be aware when the user clicks outside.

**Comment by kieuminhcanh** [comment]
You can use onClose. It's trigger when user click outside

**Comment by harry-73** [comment]
Even with `v2.0.12` `onClose` is not triggered when user clicks outside or on the 'cancel' button.
`onSubmit` behavior is OK.
