### ISSUE TITLE
[2.0.14] How to distinguish between click:outside and close events

### ISSUE THREAD

**Issue by harry-73** [kieuminhcanh/vuetify-notifier#19]
Using `.confirm`
Clicking on `close` button triggers `onClose`. Clicking on `submit` button triggers `onSubmit`.
Clicking outside the dialog triggers nothing.
I would to be notified when a user clicks outside the dialog to run some code. Before v2, I used `.catch(() => {})`

I tried to use `.dialog` with a custom component with three buttons: cancel, no (onClose), yes (onSubmit) but the only event that i can emit are `close` or `submit`

**Comment by kieuminhcanh** [comment]
I see. onClose was fired when close now. Both close button and click outside

**Comment by harry-73** [comment]
@kieuminhcanh Thanks. But I need to be able to distinguish between click on Close button and click outside.

It will be great to have a `onDismiss` for click outside and a `onClose` for click on close button. It will be more flexible.

For example, when you have a dialog with this question 'Do you want to save it' with the choice 'No' and 'Yes. So you will have the following:
- click on No ==> `onClose` ==> remove the modifications
- click on Yes ==> `onSubmit` ==> save the modifications
- click outside ==> `onDismiss` ==> do nothing

**Comment by kieuminhcanh** [comment]
onLeave was added for your case.
