### ISSUE TITLE
Incorrect theme

### ISSUE THREAD

**Issue by targetlucked69** [kieuminhcanh/vuetify-notifier#3]
I set the theme with `v-app` and got incorrect dialog theme

![Screenshot 2023-12-15 at 10 16 25 AM](https://github.com/kieuminhcanh/vuetify-notifier/assets/72330740/cec673df-6045-4e77-b7f2-7ed4f4e0f5de)

Is this repo maintained?

**Comment by kieuminhcanh** [comment]
It's work with main settings.

```javascript
const vuetify = createVuetify({
  theme:{
    defaultTheme: 'dark',
  },
})
```
