### ISSUE TITLE
Problems Occurring When Using the New Vuetify 3.5.9 with Nuxt3

### ISSUE THREAD

**Issue by mulingyuer** [kieuminhcanh/vuetify-notifier#5]
The new version of Vuetify lacks the `[data-v-app]` HTML container element, instead using:

```html
<div class="v-overlay-container"></div>
```

In cases where this div element does not exist in the entire HTML context, it needs to be manually created and inserted into the body. If it exists, it can be used directly.

I adjusted the `getVAppRoot` method under utils as follows:

```typescript
export const getVAppRoot = (): HTMLElement => {
  let overlayContainer = document.querySelector(".v-overlay-container");
  if (!overlayContainer) {
    overlayContainer = document.createElement("div");
    overlayContainer.classList.add("v-overlay-container");
    document.body.appendChild(overlayContainer);
  }
  return overlayContainer as HTMLElement;
};
```

Using this modified method, the module can be used in projects and works normally. If you do not want to change the module, you can create a div element yourself as a temporary solution:

Here is an example with Nuxt3:

```vue
<ClientOnly>
    <Teleport to="body">
      <div class="v-overlay-container" data-v-app></div>
    </Teleport>
  </ClientOnly>
```

I hope the author can fix this issue, but I am not sure if my solution is correct, although it works fine for now.

**Comment by kieuminhcanh** [comment]
Fixed. Update code for use.

![image](https://github.com/kieuminhcanh/vuetify-notifier/assets/136077/5c5e54b1-0051-4be1-b048-9afe7e04e0cc)

**Comment by mulingyuer** [comment]
> 固定。更新代码以供使用。
> 
> ![图像](https://private-user-images.githubusercontent.com/136077/321867989-5c5e54b1-0051-4be1-b048-9afe7e04e0cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MDc1MjcsIm5iZiI6MTcxMjkwNzIyNywicGF0aCI6Ii8xMzYwNzcvMzIxODY3OTg5LTVjNWU1NGIxLTAwNTEtNGJlMS1iMDQ4LTlhZmU3ZTA0ZTBjYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMlQwNzMzNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYTU5NTZhN2Q0NWU5Y2JjNjg1N2FkMTgyMmFkZDM3ZTk1NWJlMDk3ZjYwZTMyNDBlMGVkNjVlOWIwOGUyOTFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.v7WtonAs4PXeZoBU0RuizAXhDfmNFUohSSzq2iBsbJw)


The installation encountered an error while updating to version 0.0.12.：

```bash
 ERR_PNPM_LINKED_PKG_DIR_NOT_FOUND  Could not install from "E:\Code\xxxxx\src\plugins\vuetify-notifier" as it does not exist.

This error happened while installing the dependencies of vuetify-notifier@0.0.12
```

**Comment by kieuminhcanh** [comment]
@mulingyuer fixed.
