### ISSUE TITLE
Text align in confirm dialog

### ISSUE THREAD

**Issue by sivo1981** [kieuminhcanh/vuetify-notifier#6]
Currently it's not possible to align text left or right using confirm method because card text element has fixed class "text-center". Can you add this option?

https://github.com/kieuminhcanh/vuetify-notifier/blob/8a11caeb59c904ee86bdbd3a10de6932d0eff488/src/plugins/vuetify-notifier/components/NotifierDialog.vue#L38

**Comment by kieuminhcanh** [comment]
It's work now.

```
    $notifier.alert(
      {
        title: 'Confirm',
        text: 'Are you sure?',
      },
      status,
      {
        textAlign: 'left',
      }
    )

```
