### ISSUE TITLE
unable to use v1.0.0 or 1.0.1

### ISSUE THREAD

**Issue by harry-73** [kieuminhcanh/vuetify-notifier#7]
Hi,

I am able to use vuetify-notifier v1.0.0 / v1.0.1. I have the following error after installing and run my application:
failed to resolve entry for package "vuetify-notifier". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-scan]

0.0.16 is OK.

Thanks.

**Comment by sivo1981** [comment]
Same here using Nuxt.

`Uncaught SyntaxError: The requested module '/_nuxt/node_modules/vuetify-notifier/dist/vuetify-notifier.js?v=3ccfeff8' does not provide an export named 'default' (at plugin.mjs:2:8)`

**Comment by kieuminhcanh** [comment]
Please update to latest version
